version: '3'

services:
  calltaxi-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWEasd123!
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"
    expose:
      - 1433
    networks:
      - calltaxi-2025
  
  calltaxi-api:
    build:
      context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=Server=calltaxi-sql,1433;Database=CallTaxiDb;User Id=sa;Password=QWEasd123!;ConnectRetryCount=0;TrustServerCertificate=True;
    ports:
      - "5130:5130"
    networks:
      - calltaxi-2025
    links:
      - calltaxi-sql
    depends_on:
      - calltaxi-sql

networks:
  calltaxi-2025:
    driver: bridge